const express = require('express');
const path = require('path');
const ejs = require('ejs');

const app = express();
const PORT = 3000;

app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, 'views'));
app.use(express.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, 'public')));

const cards = [
  { title: 'Birthday Card', message: 'Wishing you joy, health, and lots of cake!' },
  { title: 'Thank You Note', message: 'Thank you for your support and kindness.' },
  { title: 'Festival Greeting', message: 'Warm wishes and happiness to you and your family.' }
];

app.get('/', (req, res) => {
  res.render('index', { cards });
});

app.post('/preview', (req, res) => {
  const name = req.body.name || 'Friend';
  const message = req.body.message || 'Have a great day!';
  const style = req.body.style || 'classic';

  const vulnerableTemplate = `
    <div class="preview-card ${style}">
      <div class="badge">Preview Mode</div>
      <h1>Greeting for ${name}</h1>
      <p>${message}</p>
      <small>Generated by Greeting Studio</small>
    </div>
  `;

  try {
    const html = ejs.render(vulnerableTemplate, { sample: 'demo' });
    res.render('preview', { html, name, message, style, error: null });
  } catch (err) {
    res.render('preview', { html: null, name, message, style, error: err.message });
  }
});

app.get('/safe-preview', (req, res) => {
  const name = req.query.name || 'Friend';
  const message = req.query.message || 'Have a great day!';
  const style = req.query.style || 'classic';
  res.render('safe-preview', { name, message, style });
});

app.listen(PORT, () => {
  console.log(`SSTI lab running at http://127.0.0.1:${PORT}`);
});